# -*- coding: utf-8 -*-
"""Copy of mytrial1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FHpwNEtTn6kxv9I9vyC6Lyj51UzKgRGK
"""

!pip install -q torch torchaudio transformers numpy scikit-learn tqdm scipy soundfile

import torch, numpy as np
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device, "| gpu:", torch.cuda.get_device_name(0) if device.type=="cuda" else "none")

import os
import json
import torch
import torch.nn as nn
import torchaudio
import numpy as np
import soundfile as sf

from torch.utils.data import Dataset, DataLoader
from transformers import AutoModel
from tqdm import tqdm
from scipy.stats import pearsonr, spearmanr

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

CKPT_DIR = "/content/drive/MyDrive/singmos_ckpts"
os.makedirs(CKPT_DIR, exist_ok=True)

!git clone https://huggingface.co/datasets/TangRain/SingMOS

DATA_ROOT = "SingMOS"

with open(f"{DATA_ROOT}/info/split.json") as f:
    split_data = json.load(f)["singmos"]

with open(f"{DATA_ROOT}/info/score.json") as f:
    score_data = json.load(f)["utterance"]

def build_items(utt_ids, score_data, data_root):
    items = []
    for utt_id in utt_ids:
        info = score_data[utt_id]
        wav_path = os.path.join(data_root, info["wav"])
        mos = float(info["score"]["mos"])
        items.append((wav_path, mos))
    return items

train_items = build_items(split_data["train"], score_data, DATA_ROOT)
val_items   = build_items(split_data["valid"], score_data, DATA_ROOT)
test_items_v1 = build_items(split_data["eval_v1"], score_data, DATA_ROOT)
test_items_v2 = build_items(split_data["eval_v2"], score_data, DATA_ROOT)

# compute train target mean/std once
train_mos_arr = np.array([mos for _, mos in train_items], dtype=np.float32)
MOS_MEAN = float(train_mos_arr.mean())
MOS_STD  = float(train_mos_arr.std() + 1e-6)
print("MOS mean/std:", MOS_MEAN, MOS_STD)

def mos_to_z(y):      # y in [1,5]
    return (y - MOS_MEAN) / MOS_STD

def z_to_mos(z):      # map back
    return z * MOS_STD + MOS_MEAN

class SingMOSDataset(Dataset):
    def __init__(self, items, sample_rate=16000):
        self.items = items
        self.sr = sample_rate

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        path, mos = self.items[idx]
        wav, sr = sf.read(path, dtype="float32")

        if wav.ndim == 2:
            wav = wav.mean(axis=1)  # NumPy

        wav = torch.from_numpy(wav)

        if sr != self.sr:
            wav = torchaudio.functional.resample(wav, sr, self.sr)

        return wav, torch.tensor(mos, dtype=torch.float32)

def collate_fn(batch):
    wavs, mos = zip(*batch)
    lengths = torch.tensor([w.shape[0] for w in wavs])

    wavs = torch.nn.utils.rnn.pad_sequence(
        wavs, batch_first=True
    )

    mask = torch.arange(wavs.size(1))[None, :] < lengths[:, None]
    return wavs, mask, torch.stack(mos)

import numpy as np
import torch
from torch.utils.data import WeightedRandomSampler, DataLoader

def make_bin_weights(mos_list, bins=(1,2,3,4,5.01), max_ratio=10.0):
    """
    bins: score buckets (4 bins by default)
    max_ratio: caps oversampling so rare bins don't dominate too hard
    """
    mos = np.array(mos_list, dtype=np.float32)
    bin_idx = np.digitize(mos, bins) - 1  # 0..len(bins)-2
    n_bins = len(bins) - 1

    counts = np.bincount(bin_idx, minlength=n_bins).astype(np.float32)
    counts[counts == 0] = 1.0  # avoid divide-by-zero if a bin is empty

    inv = 1.0 / counts
    inv = inv / inv.mean()  # normalize so average weight ~ 1

    # cap extreme oversampling
    inv = np.clip(inv, 1.0 / max_ratio, max_ratio)

    weights = inv[bin_idx]
    return torch.tensor(weights, dtype=torch.double), counts

# --- build weights from train_items ---
train_mos = [mos for _, mos in train_items]
weights, counts = make_bin_weights(train_mos)

train_mos_arr = np.array(train_mos, dtype=np.float32)
MOS_MEAN = float(train_mos_arr.mean())
MOS_STD  = float(train_mos_arr.std() + 1e-6)

print("MOS mean/std:", MOS_MEAN, MOS_STD)

print("Train bin counts [1-2,2-3,3-4,4-5]:", counts.astype(int).tolist())
print("Weight stats:", float(weights.min()), float(weights.mean()), float(weights.max()))

sampler = WeightedRandomSampler(weights, num_samples=len(weights), replacement=True)

# IMPORTANT: use sampler, do NOT use shuffle=True
train_loader = DataLoader(
    SingMOSDataset(train_items),
    batch_size=8,
    sampler=sampler,
    collate_fn=collate_fn
)

val_loader = DataLoader(
    SingMOSDataset(val_items),
    batch_size=8,
    shuffle=False,
    collate_fn=collate_fn
)

train_ds = SingMOSDataset(train_items)
val_ds   = SingMOSDataset(val_items)

from torch.utils.data import DataLoader, WeightedRandomSampler

sampler = WeightedRandomSampler(weights, num_samples=len(weights), replacement=True)

train_loader = DataLoader(
    train_ds,
    batch_size=16,
    sampler=sampler,      # <- this replaces shuffle
    collate_fn=collate_fn
)

val_loader = DataLoader(b
    val_ds,
    batch_size=16,
    shuffle=False,
    collate_fn=collate_fn
)

import torch
import torch.nn as nn
from transformers import AutoModel

class MERTEncoder(nn.Module):
    def __init__(self, model_name="m-a-p/MERT-v1-95M", layer_mode="last4", device=None):
        super().__init__()
        self.model = AutoModel.from_pretrained(model_name, trust_remote_code=True)
        if device is not None:
            self.model = self.model.to(device)
        self.model.eval()
        for p in self.model.parameters():
            p.requires_grad = False
        self.layer_mode = layer_mode
        self.hidden_size = self.model.config.hidden_size

    @torch.no_grad()
    def forward(self, wav, mask):
        dev = next(self.model.parameters()).device
        wav = wav.to(dev)
        mask = mask.to(dev)

        outputs = self.model(
            wav,
            attention_mask=mask,
            output_hidden_states=True,
            return_dict=True
        )

        if self.layer_mode == "last":
            h = outputs.last_hidden_state
        elif self.layer_mode == "last4":
            h = torch.stack(outputs.hidden_states[-4:]).mean(dim=0)
        else:
            raise ValueError(f"Unknown layer_mode: {self.layer_mode}")

        return h

def mean_std_pooling(h, frame_mask=None, eps=1e-6):
    """
    h: (B, T, D)
    frame_mask: (B, T) bool
    return: (B, 2D) concat(mean, std)
    """
    if frame_mask is None:
        mean = h.mean(dim=1)
        std  = h.std(dim=1)
        return torch.cat([mean, std], dim=-1)

    m = frame_mask.float().unsqueeze(-1)        # (B,T,1)
    denom = m.sum(dim=1).clamp(min=1.0)         # (B,1)

    mean = (h * m).sum(dim=1) / denom           # (B,D)

    var = ((h - mean.unsqueeze(1)) ** 2) * m
    var = var.sum(dim=1) / denom
    std = torch.sqrt(var + eps)                 # (B,D)

    return torch.cat([mean, std], dim=-1)

class SingMOSModel(nn.Module):
    def __init__(self, encoder):
        super().__init__()
        self.encoder = encoder
        self.norm = nn.LayerNorm(2 * encoder.hidden_size)
        self.regressor = MOSRegressor(2 * encoder.hidden_size)

    def forward(self, wav, mask):
        h = self.encoder(wav, mask)  # (B,T,D)
        B, T, _ = h.shape

        valid_samples = mask.sum(dim=1)
        L = mask.size(1)
        valid_frames = torch.ceil(valid_samples.float() * T / L).clamp(1, T).long()
        frame_mask = torch.arange(T, device=h.device)[None, :] < valid_frames[:, None]

        pooled = mean_std_pooling(h, frame_mask=frame_mask)   # (B,2D)
        pooled = self.norm(pooled)
        z_pred = self.regressor(pooled)                       # (B,)
        return z_pred

class MOSRegressor(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 512),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(512, 1)
        )

    def forward(self, x):
        return self.net(x).squeeze(-1)

device = "cuda" if torch.cuda.is_available() else "cpu"

encoder = MERTEncoder(device=device)   # frozen or partially unfrozen, your choice
model = SingMOSModel(encoder).to(device)

def evaluate(model, loader, device, return_preds=False):
    model.eval()
    ys, y_hats = [], []
    with torch.no_grad():
        for wav, mask, y in loader:
            wav, mask = wav.to(device), mask.to(device)
            z_hat = model(wav, mask)
            mos_hat = z_to_mos(z_hat).clamp(1.0, 5.0)

            ys.append(y.numpy())
            y_hats.append(mos_hat.cpu().numpy())

    ys = np.concatenate(ys)
    y_hats = np.concatenate(y_hats)

    mae = np.mean(np.abs(ys - y_hats))
    rmse = np.sqrt(np.mean((ys - y_hats) ** 2))
    pearson = pearsonr(ys, y_hats)[0]
    spearman = spearmanr(ys, y_hats)[0]
    if return_preds:
        return mae, rmse, pearson, spearman, ys, y_hats
    return mae, rmse, pearson, spearman

val_mae, val_rmse, val_p, val_s, ys, y_hats = evaluate(
    model, val_loader, device, return_preds=True
)

_, _, _, _, ys, y_hats = evaluate(model, val_loader, device, return_preds=True)
print("Val y_std:", ys.std(), "Pred std:", y_hats.std())

def save_checkpoint(path, epoch, model, optimizer, best_pearson):
    torch.save({
        "epoch": epoch,
        "model": model.state_dict(),
        "optimizer": optimizer.state_dict(),
        "best_pearson": best_pearson
    }, path)


def load_checkpoint(path, model, optimizer, device):
    # IMPORTANT: weights_only=False because your old checkpoint contains numpy scalars
    ckpt = torch.load(path, map_location=device, weights_only=False)

    model.load_state_dict(ckpt["model"])

    try:
        optimizer.load_state_dict(ckpt["optimizer"])
    except Exception as e:
        print("Warning: optimizer state not loaded (likely param groups changed).", e)

    best_pearson = ckpt.get("best_pearson", None)
    if hasattr(best_pearson, "item"):
        best_pearson = best_pearson.item()

    return ckpt["epoch"] + 1, best_pearson

# =============================
# CORRELATION-AWARE HYBRID LOSS
# =============================

def pearson_corr(x, y, eps=1e-8):
    x = x - x.mean()
    y = y - y.mean()
    return (x * y).sum() / (
        torch.sqrt((x * x).sum() + eps) *
        torch.sqrt((y * y).sum() + eps)
    )

def hybrid_loss(z_hat, y_true_mos, MOS_MEAN, MOS_STD, alpha=0.6):
    # convert MOS to standardized z-space
    z_true = (y_true_mos - MOS_MEAN) / MOS_STD

    l1 = torch.nn.functional.l1_loss(z_hat, z_true)
    corr = pearson_corr(z_hat, z_true)

    # minimize L1 and maximize correlation
    return alpha * l1 + (1 - alpha) * (1 - corr)

def train(model, train_loader, val_loader, device, epochs=20, lr=1e-4):

    model.to(device)

    optimizer = torch.optim.Adam(
        list(model.regressor.parameters()) + list(model.norm.parameters()),
        lr=lr
    )

    best_p = -1

    for epoch in range(epochs):
        model.train()
        losses = []

        for wav, mask, y in tqdm(train_loader, desc=f"Epoch {epoch}"):

            wav = wav.to(device)
            mask = mask.to(device)
            y = y.to(device)

            z_hat = model(wav, mask)

            loss = hybrid_loss(
                z_hat,
                y,
                MOS_MEAN,
                MOS_STD,
                alpha=0.6
            )

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            losses.append(loss.item())

        # evaluate
        val_mae, val_rmse, val_p, val_s, ys, y_hats = evaluate(
            model, val_loader, device, return_preds=True
        )

        print(
            f"Epoch {epoch} | "
            f"Loss {np.mean(losses):.4f} | "
            f"Val MAE {val_mae:.3f} | "
            f"RMSE {val_rmse:.3f} | "
            f"P {val_p:.3f} | "
            f"S {val_s:.3f} | "
            f"y_std {ys.std():.3f} | "
            f"pred_std {y_hats.std():.3f}"
        )

        if val_p > best_p:
            best_p = val_p
            torch.save(model.state_dict(), f"{CKPT_DIR}/best_head.pt")

    print("Best Pearson:", best_p)

def train(
    model,
    train_loader,
    val_loader,
    device,
    epochs=30,
    lr_head=1e-4,
    lr_encoder=1e-5,
    resume_ckpt=None
):
    optimizer = torch.optim.Adam(
    list(model.regressor.parameters()) + list(model.norm.parameters()),
    lr=1e-4
)

    criterion = nn.L1Loss()

    start_epoch = 0
    best_pearson = -1

    if resume_ckpt and os.path.exists(resume_ckpt):
        start_epoch, best_pearson = load_checkpoint(
            resume_ckpt, model, optimizer, device
        )
        print(f"Resumed from epoch {start_epoch} | best pearson so far {best_pearson}")

    for epoch in range(start_epoch, epochs):
        model.train()
        losses = []

        for wav, mask, y in tqdm(train_loader, desc=f"Epoch {epoch}"):
            wav = wav.to(device)
            mask = mask.to(device)
            y = y.to(device)

            z_hat = model(wav, mask)
            loss = hybrid_loss(z_hat, y, alpha=0.6)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            losses.append(loss.item())

        # If you updated evaluate to return rmse:
        val_mae, val_rmse, val_p, val_s = evaluate(model, val_loader, device)

        print(
            f"Epoch {epoch} | "
            f"Train MAE {np.mean(losses):.3f} | "
            f"Val MAE {val_mae:.3f} | "
            f"Val RMSE {val_rmse:.3f} | "
            f"P {val_p:.3f} | S {val_s:.3f}"
        )

        save_checkpoint(
            f"{CKPT_DIR}/latest.pt",
            epoch,
            model,
            optimizer,
            best_pearson
        )

        if val_p > best_pearson:
            best_pearson = val_p
            save_checkpoint(
                f"{CKPT_DIR}/best.pt",
                epoch,
                model,
                optimizer,
                best_pearson
            )

print("train_loader exists?", "train_loader" in globals())
print("model exists?", "model" in globals())
print("train function exists?", "train" in globals())

import torch

device = torch.device("cpu")

model = model.to(device)
model.eval()

# optional: make sure no leftover CUDA tensors are referenced
torch.cuda.empty_cache()

wavs, mask, mos = next(iter(train_loader))
print("wavs device:", wavs.device)

# move batch
wavs, mask = wavs.to(device), mask.to(device)
print("wavs device after .to:", wavs.device)

# check model param device
print("model param device:", next(model.parameters()).device)

import torch
import sys

# Make sure model is CPU
device = torch.device("cpu")
model = model.to(device).eval()

# Remove old hooks if any
for m in model.modules():
    if hasattr(m, "_dbg_hook"):
        m._dbg_hook.remove()

def hook(mod, inputs):
    # Some modules receive no positional inputs
    if len(inputs) == 0:
        return

    x = inputs[0]

    if torch.is_tensor(x) and x.is_cuda:
        msg = (
            f"CUDA INPUT ENTERS: {mod.__class__.__name__} | "
            f"device={x.device} dtype={x.dtype} shape={tuple(x.shape)}"
        )
        print(msg)
        sys.stdout.flush()
        raise RuntimeError(msg)

# Attach hook only to encoder submodules
for m in model.encoder.modules():
    m._dbg_hook = m.register_forward_pre_hook(hook)

# Run one forward pass
wavs, mask, mos = next(iter(train_loader))
wavs, mask = wavs.to(device), mask.to(device)

with torch.no_grad():
    _ = model.encoder(wavs, mask)

print("Encoder forward completed without CUDA input.")

import numpy as np
import torch
from tqdm import tqdm

device = torch.device("cpu")
model = model.to(device)
model.eval()

def batch_to_features(wavs, mask):
    with torch.no_grad():
        h = model.encoder(wavs, mask)     # (B,T,D)
        B, T, D = h.shape

        valid_samples = mask.sum(dim=1)   # (B,)
        L = mask.size(1)
        valid_frames = torch.ceil(valid_samples.float() * T / L).clamp(1, T).long()

        frame_mask = torch.arange(T, device=h.device)[None, :] < valid_frames[:, None]

        pooled = mean_std_pooling(h, frame_mask=frame_mask)  # (B, 2D)
        pooled = model.norm(pooled)                          # (B, 2D)
        return pooled

def extract_features(loader, max_batches=None):
    Xs, ys = [], []
    for bi, (wavs, mask, mos) in enumerate(tqdm(loader)):
        if max_batches is not None and bi >= max_batches:
            break
        wavs = wavs.to(device)
        mask = mask.to(device)
        feats = batch_to_features(wavs, mask)
        Xs.append(feats.numpy())      # already CPU
        ys.append(mos.numpy())        # already CPU
    X = np.concatenate(Xs, axis=0)
    y = np.concatenate(ys, axis=0)
    return X, y

# quick test first (recommended)
X_train, y_train = extract_features(train_loader, max_batches=10)
X_val,   y_val   = extract_features(val_loader,   max_batches=5)

print("TEST shapes:", X_train.shape, y_train.shape, X_val.shape, y_val.shape)
print("Train y mean/std:", y_train.mean(), y_train.std())
print("Val y mean/std:", y_val.mean(), y_val.std())

train(
    model,
    train_loader,
    val_loader,
    device,
    epochs=30,
    resume_ckpt=None
)

import matplotlib.pyplot as plt

plt.scatter(ys, y_hats, alpha=0.3)
plt.xlabel("True MOS")
plt.ylabel("Predicted MOS")
plt.plot([1,5],[1,5],'r--')
plt.show()

print("True std:", np.std(ys))
print("Pred std:", np.std(y_hats))

train_ys = []
for wavs, mask, mos in train_loader:
    train_ys.extend(mos.cpu().numpy())
train_ys = np.array(train_ys)

print("Train mean:", train_ys.mean())
print("Train std:", train_ys.std())

wavs, mask, mos = next(iter(train_loader))
print("wavs:", wavs.shape, wavs.dtype, wavs.min().item(), wavs.max().item())
print("mask:", mask.shape, mask.dtype, mask[:2, :10])
print("mos:", mos.shape, mos.dtype, mos[:10])

import numpy as np
import torch

ys, y_hats = [], []

model.eval()
with torch.no_grad():
    for wav, mask, y in loader:
        wav = wav.to(device)
        mask = mask.to(device)
        y = y.to(device)

        z_hat = model(wav, mask)
        y_hat = (z_hat * MOS_STD + MOS_MEAN).clamp(1.0, 5.0)

        ys.append(y.cpu().numpy())
        y_hats.append(y_hat.cpu().numpy())

ys = np.array(ys)
y_hats = np.array(y_hats)

print("Val mean:", ys.mean())
print("Val std :", ys.std())
print("Pred mean:", y_hats.mean())
print("Pred std :", y_hats.std())
print("Pred min/max:", y_hats.min(), y_hats.max())

print("Train target mean:", np.mean(train_ys))
print("Train target std:", np.std(train_ys))

print("Val target mean:", np.mean(ys))
print("Val target std:", np.std(ys))

print("Pred mean:", np.mean(y_hats))
print("Pred std:", np.std(y_hats))

def per_bin_mae(y, yhat):
    bins = [1,2,3,4,5.01]
    idx = np.digitize(y, bins)-1
    for b in range(4):
        mask = idx==b
        if mask.sum()>0:
            print(f"{bins[b]}-{bins[b+1]}:",
                  np.mean(np.abs(y[mask]-yhat[mask])))

durations = []
human_mos = []

for path, mos in val_items:
    wav, sr = sf.read(path)
    durations.append(len(wav) / sr)
    human_mos.append(mos)

durations = np.array(durations)
human_mos = np.array(human_mos)

r, p = pearsonr(durations, human_mos)
print("Duration vs MOS r:", r)

import numpy as np

rms_vals = []
human_mos = []

for path, mos in val_items:
    wav, sr = sf.read(path)
    if wav.ndim == 2:
        wav = wav.mean(axis=1)
    rms = np.sqrt(np.mean(wav**2))
    rms_vals.append(rms)
    human_mos.append(mos)

rms_vals = np.array(rms_vals)
human_mos = np.array(human_mos)

r, p = pearsonr(rms_vals, human_mos)
print("RMS vs MOS r:", r)

!pip -q install librosa
import librosa
import numpy as np
from scipy.stats import pearsonr, spearmanr
import soundfile as sf

def pitch_stats(path, target_sr=16000):
    y, sr = sf.read(path, dtype="float32")
    if y.ndim == 2:
        y = y.mean(axis=1)
    if sr != target_sr:
        y = librosa.resample(y, orig_sr=sr, target_sr=target_sr)
        sr = target_sr

    # pYIN returns f0 (Hz) with nan for unvoiced, and a voiced flag
    f0, voiced_flag, voiced_prob = librosa.pyin(
        y,
        fmin=librosa.note_to_hz("C2"),
        fmax=librosa.note_to_hz("C7"),
        sr=sr,
        frame_length=2048,
        hop_length=256
    )

    if f0 is None:
        return np.nan, np.nan, np.nan, 0.0

    voiced_f0 = f0[voiced_flag]
    voiced_ratio = float(np.mean(voiced_flag)) if len(voiced_flag) > 0 else 0.0

    if voiced_f0.size < 5:
        return np.nan, np.nan, np.nan, voiced_ratio

    # log-scale is better for pitch (cents-ish)
    log_f0 = np.log(voiced_f0)

    f0_mean = float(np.mean(log_f0))
    f0_std  = float(np.std(log_f0))
    # frame-to-frame instability
    f0_diff_std = float(np.std(np.diff(log_f0))) if log_f0.size >= 2 else np.nan

    return f0_mean, f0_std, f0_diff_std, voiced_ratio

# choose val_items or train_items; start with val_items
f0_means, f0_stds, f0_diff_stds, voiced_ratios, mos_list = [], [], [], [], []

for path, mos in val_items:
    m, s, ds, vr = pitch_stats(path)
    f0_means.append(m)
    f0_stds.append(s)
    f0_diff_stds.append(ds)
    voiced_ratios.append(vr)
    mos_list.append(mos)

f0_means = np.array(f0_means)
f0_stds = np.array(f0_stds)
f0_diff_stds = np.array(f0_diff_stds)
voiced_ratios = np.array(voiced_ratios)
mos_list = np.array(mos_list)

def corr(x, y, name):
    mask = np.isfinite(x) & np.isfinite(y)
    r = pearsonr(x[mask], y[mask])[0]
    s = spearmanr(x[mask], y[mask])[0]
    print(f"{name}: pearson={r:.3f}, spearman={s:.3f}, n={mask.sum()}")

corr(f0_stds, mos_list, "Pitch std (log f0) vs MOS")
corr(f0_diff_stds, mos_list, "Pitch instability (diff std) vs MOS")
corr(voiced_ratios, mos_list, "Voiced ratio vs MOS")

from scipy.stats import pearsonr

r, p = pearsonr(feature, human_mos)
print("Pearson r:", r)
print("p-value:", p)

torch.cuda.empty_cache()

# peek at one batch distribution
wavs, mask, y = next(iter(train_loader))
print("Batch mos min/mean/max:", y.min().item(), y.mean().item(), y.max().item())
print("Count <2:", (y < 2).sum().item(), "out of", len(y))

test_loader_v1 = DataLoader(SingMOSDataset(test_items_v1), batch_size=16, collate_fn=collate_fn)
test_loader_v2 = DataLoader(SingMOSDataset(test_items_v2), batch_size=16, collate_fn=collate_fn)

ckpt = torch.load(f"{CKPT_DIR}/best.pt", map_location=device, weights_only=False)
model.load_state_dict(ckpt["model"])
print("Eval v1:", evaluate(model, test_loader_v1, device))
print("Eval v2:", evaluate(model, test_loader_v2, device))